# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2j" do
  version "0.0.14"

  on_macos do
    on_intel do
      sha256 "cd7f9ef87be267b9e03c132efb98cdef6ed4472dbaef9b8f7b216edbf10abd21"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5a79a6f4095f0e1a80aa168f3f0bdc828836fa5795a312b51b572bfe197903bc"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1954c658c874e878db429c42f06da43510aca7c5db891400034b8fc4b96a962"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "287003501e01b6aaf3481de98530a21d8077de616ef85962a6ede956e8271cd9"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "c2j"
  desc "c2j job system"
  homepage "https://github.com/colony-2/c2j"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2j"

  # No zap stanza required

end
