# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2j" do
  version "0.0.15"

  on_macos do
    on_intel do
      sha256 "1cf76f8c4799c86c590af30a5a423ef524b157f39b58a4c18afc8cd11c0489d8"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52fe3b1ac0603a455cd82256b9b89a544e63893d255ae9d600da10278a628a49"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4fefbffa8b4f74c1436f8fb5e99696c1591ddeaa637dfcc39a12434f50f338c4"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fa7cd512769b9eb9b86539b029ab2d4b316d25013658a0f52592444bfa2e01ae"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "c2j"
  desc "c2j job system"
  homepage "https://github.com/colony-2/c2j"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2j"

  # No zap stanza required

end
