# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2j" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "7f6f02d106e9f729270544970ca61106f1516f71ae578fda0e4819dd3729e043"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f18a96d7b452641d4f382aecd2c5fe1e2bf916c2cfbc21bde885f0353ed1441c"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f63d4d0789dcffe5549b186a38acfd53b03d6c8e8698793538fd3859b564cf70"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "41c04d6a49c830c6f7d8d7e9df56c9791c2c10a2ca111e78732bbb3c4d494211"
      url "https://github.com/colony-2/c2j-release/releases/download/v#{version}/c2j_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "c2j"
  desc "c2j job system"
  homepage "https://github.com/colony-2/c2j"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2j"

  # No zap stanza required

end
