# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2m" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_x86_64.tar.gz"
      sha256 "4231795b5f9d1cd2ae869d85da3ec164f4c0055cf6b46cdf0f2bb70f8e6dde5e"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_arm64.tar.gz"
      sha256 "7f6fc9564b30674671d4e435a91d50b9057dfbbd20b259f2cf4924d18931be1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_x86_64.tar.gz"
      sha256 "637a100b1d3f2c4e6c601f4f3d2247bb6f3f0389cc226d782e35acf7c7c708cd"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_arm64.tar.gz"
      sha256 "a52b2629f4c09a2ddfcb047a811d761a162ff643409e71a1393a540ce09e35dd"
    end
  end

  name "c2m"
  desc "Sandboxing shell for running AI coding agents inside Docker containers"
  homepage "https://github.com/colony-2/c2m"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2m"

  # No zap stanza required

end
