# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2m" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_x86_64.tar.gz"
      sha256 "2327580e6cb95025945af616ba396ff46c091a180cdc645349719105101537ce"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_arm64.tar.gz"
      sha256 "1e8c3ad6e0e894bafed5fb2511358eb622d9d9fdb029d98ae5e47f95d38117fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_x86_64.tar.gz"
      sha256 "4d1243d372b3371c3601cb0cf3d1e2914d319c409a35dccde7cd2d20570d3f58"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_arm64.tar.gz"
      sha256 "6ecb315ed3aed478370a70704c65201023df7c7e11174f4da38f1a290bcb08c9"
    end
  end

  name "c2m"
  desc "c2m agent memory system"
  homepage "https://github.com/colony-2/c2m"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2m"

  # No zap stanza required

end
