# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2m" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_x86_64.tar.gz"
      sha256 "f737a665dd36df905c391008cd39e1062172afb32ad6cee6a28c101c83330542"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Darwin_arm64.tar.gz"
      sha256 "12928e689ddd66fe1c95d55ccc5ac5a565afb6eeb88de6334cd591e4c96dfd1b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_x86_64.tar.gz"
      sha256 "5680bd4c0eed6a847f4bac3f4be6825cf799875b72de466ec344ebf5d8b301e8"
    end
    on_arm do
      url "https://github.com/colony-2/c2m/releases/download/v#{version}/c2m_#{version}_Linux_arm64.tar.gz"
      sha256 "7ffd9f91054af947caeb4657f78482f8d49d698450da19535feada1587a8a584"
    end
  end

  name "c2m"
  desc "c2m agent memory system"
  homepage "https://github.com/colony-2/c2m"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2m"

  # No zap stanza required

end
