# This file was generated by GoReleaser. DO NOT EDIT.
cask "c2r" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "1566611c85b9533fd5bf8565ef498217c303b6a04ff12cba39bd10b1e4a9eab5"
      url "https://github.com/colony-2/c2r/releases/download/v#{version}/c2r_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3e90f508dd6c4534a7d5380d4c9063c96197bd65bffdaad56b6f966ef702c5a3"
      url "https://github.com/colony-2/c2r/releases/download/v#{version}/c2r_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d05cd2d720b88b4506758f7a42a0009912c314c6e6654d065758eff8403d1c54"
      url "https://github.com/colony-2/c2r/releases/download/v#{version}/c2r_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cb85a17dbfede82035d57230e14dbcf2d9a01355f1c28ad326328f540ad8e6ea"
      url "https://github.com/colony-2/c2r/releases/download/v#{version}/c2r_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "c2r"
  desc "c2r"
  homepage "https://github.com/colony-2/c2r"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c2r"

  # No zap stanza required

end
