# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobdb" do
  version "0.0.24"

  on_macos do
    on_arm do
      sha256 "ad92ca894cd6ee4b9daa158973eeccd7c552b9d11874e672feeda7053bde51da"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eebe056541e613d47e3eaa7aeb9cee00b5b15d0e56037b7054218efa506f7623"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8d9ed39e7d1c6f45e4e36ab7aa3793b0be5539b6127954d8b418bf15841a9538"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "03fa1bd473117cbda35f1757687082748df41df1df6b41614b1dd3a241687a34"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "jobdb"
  desc "jobdb"
  homepage "https://github.com/colony-2/jobdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobdb"

  # No zap stanza required
end
