# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobdb" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "558e930d85bdb9b7599a6e67f546015e063ff969c681c9717ad6a7a13c50b63c"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "480b53c0d81c78097f412e4436059cab1098c67e7ce3448838d276895db8a68b"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8406e066f086dd6890d3f5e143cc5135d5d2dfa2fa18f1b37f2fb3bfe4e1611"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "89a52c995a080fb86357fc030378d7b1d402b8be1a69c32e368ae105058b68fc"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "jobdb"
  desc "jobdb"
  homepage "https://github.com/colony-2/jobdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobdb"

  # No zap stanza required

end
