# This file was generated by GoReleaser. DO NOT EDIT.
cask "jobdb" do
  version "0.0.23"

  on_macos do
    on_arm do
      sha256 "5cc2fa478766242a72352e47b25337ce7b7c0561379db85367298ee80c52ccb8"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5ebe795526ac30165517897102d90c1aa5756ec35c93ea77e253a866df486c2"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c34d5785877c2958e4c14f280cc372849501c8fa29c6154c9413a4e785d9adb4"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1af6c24e894ee07bba70a0a0e2712421779031a3db25d5c37e14ef68ab76661b"
      url "https://github.com/colony-2/jobdb/releases/download/v#{version}/jobdb_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "jobdb"
  desc "jobdb"
  homepage "https://github.com/colony-2/jobdb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jobdb"

  # No zap stanza required
end
