# This file was generated by GoReleaser. DO NOT EDIT.
cask "shai" do
  name "shai"
  desc "Sandboxing shell for running AI coding agents inside Docker containers"
  homepage "https://github.com/colony-2/shai"
  version "0.0.1-rc2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shai"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_x86_64.tar.gz"
      sha256 "3feaac23b35f91e3a7153ef6b6360882e08a55ae18cf9bdafac0f1f6afbbf523"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_arm64.tar.gz"
      sha256 "0f7b53384d54bcf05332e962c8c43f0bbf14ee133b72b36a9ec7d60ce2a24ff1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_x86_64.tar.gz"
      sha256 "a39fd0b49b62b8536326a3a6179c832092657f4f89ed723893c1b31b4d2ff91c"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_arm64.tar.gz"
      sha256 "fdf03819a2bfae60c74e5faaaa66b2f03e23d8d701802df485e14450479171bb"
    end
  end

  # No zap stanza required
end
