# This file was generated by GoReleaser. DO NOT EDIT.
cask "shai" do
  name "shai"
  desc "Sandboxing shell for running AI coding agents inside Docker containers"
  homepage "https://github.com/colony-2/shai"
  version "0.0.6-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shai"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b4d436412bbf68c4d2b1586eaa1376e8088dea47090a59946cdd72d51fbfcddc"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_arm64.tar.gz"
      sha256 "3b9c8f1defb4823e5c6ad8108a424df08fe75bcd7f69e0ac59b38649f3df5977"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_x86_64.tar.gz"
      sha256 "e4793f9be95433e93b804daf8f74f5eb092edd8f55ca586a6fff4a309d1d6d29"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_arm64.tar.gz"
      sha256 "f53537aacc7d835036e3e539d161935a99d91571f0139ae8e19366d5db212b32"
    end
  end

  # No zap stanza required
end
