# This file was generated by GoReleaser. DO NOT EDIT.
cask "shai" do
  version "0.0.9"

  on_macos do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_x86_64.tar.gz"
      sha256 "12e3c925e254b8c0ef342a75a51ace6828e63c1d2a4f1743c6859875c620b46e"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Darwin_arm64.tar.gz"
      sha256 "6f8e63464631af7d29abe58b11d4bfe145a997751cc29bf7ae5312cf215474a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_x86_64.tar.gz"
      sha256 "6f022d3884b999554e8014d28881a1fd2b7d8692f383f96511f6292a7276d512"
    end
    on_arm do
      url "https://github.com/colony-2/shai/releases/download/v#{version}/shai_#{version}_Linux_arm64.tar.gz"
      sha256 "10944595bf44e39999d60d53108695d949e90d9a3c89729fbb337d69aff8972a"
    end
  end

  name "shai"
  desc "Sandboxing shell for running AI coding agents inside Docker containers"
  homepage "https://github.com/colony-2/shai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shai"

  # No zap stanza required

end
