# This file was generated by GoReleaser. DO NOT EDIT.
cask "swf-go" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "8e409f38d2a95edd1e4296013b807042c3fb4ff0e59958613bed82aa322d6b5e"
      url "https://github.com/colony-2/swf-go/releases/download/v#{version}/swfd_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "851d5c78ddd193ef78041e599e3f388c046ba0f4da30528181de7eb3db1bf5e8"
      url "https://github.com/colony-2/swf-go/releases/download/v#{version}/swfd_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0cd8b4f808b3b1bddc3506da862ebee66e4a239d5c736440d9e58c89195bc1f"
      url "https://github.com/colony-2/swf-go/releases/download/v#{version}/swfd_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c1cbc1b9a8145469ce450ada5f8eb0e83112feb82590d29354d00945258cf5dd"
      url "https://github.com/colony-2/swf-go/releases/download/v#{version}/swfd_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "swf-go"
  desc "swfd"
  homepage "https://github.com/colony-2/swf-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swf-go"

  # No zap stanza required

end
